name: Build MPP package

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: jtdor/build-deb-action@v1
        with:
          before-build-hook: |
            apt install git
            ls
            tar --exclude='.git' --exclude='debian' -czf ../mpp_1.6.0.orig.tar.gz ./
            ls ../
          buildpackage-opts: -sa
      - name: Upload DEB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: debian/artifacts/*